services:
  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: catalog-service-es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./catalog-data:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  api:
    build:
      context: ../
      dockerfile: deploy/dockerfiles/browser/api.dockerfile
    platform: linux/amd64
    # command: pnpm run node /build/app.js
    environment:
      - NODE_ENV=development
      - PORT=8000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD
      - CACHE_REDIS_URL=redis://redis:6379/1
      - RATE_LIMITER_REDIS_URL=redis://redis:6379/2
    ports:
      - 888:8000
    volumes:
      - ./dataset-metadata:/app/dataset-metadata
      - ./graphql-api/src:/app/graphql-api/src
    depends_on:
      - elasticsearch
      - redis
volumes:
  redis_data:
