- op: replace
  path: /spec/nodeSets
  value:
    - name: master
      count: 1
      config: # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
        node.roles: ['master']
        ingest.geoip.downloader.enabled: false
      podTemplate:
        metadata:
          labels:
            role: master
        spec:
          automountServiceAccountToken: true
          serviceAccountName: es-snaps
          affinity:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
            - name: install-plugins
              command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: 50Gi
    - name: data-blue
      count: 2
      config: # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
        node.roles: ['data']
        ingest.geoip.downloader.enabled: false
      podTemplate:
        metadata:
          labels:
            role: data
        spec:
          automountServiceAccountToken: true
          serviceAccountName: es-snaps
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
            - name: install-plugins
              command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: '-Xms16g -Xmx16g'
              resources:
                requests:
                  cpu: 2
                  memory: 24Gi
                limits:
                  cpu: 3
                  memory: 24Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: 200Gi
