---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
labels:
  - pairs:
      deployment: 'green'
    includeSelectors: true
    includeTemplates: true
nameSuffix: '-green'
images:
  - name: gcr.io/exac-gnomad/gnomad-api
    newTag: '22b9f79b'
  - name: gcr.io/exac-gnomad/gnomad-browser
    newTag: '22b9f79b'
replacements:
  - source:
      fieldPath: metadata.name
      kind: Service
      name: gnomad-api
      version: v1
    targets:
      - fieldPaths:
          - spec.template.spec.containers.0.env.0.value
        options:
          delimiter: /
          index: 2
        select:
          group: apps
          kind: Deployment
          name: gnomad-browser
          version: v1
