---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-api
  labels:
    component: gnomad-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gnomad-api
  template:
    metadata:
      labels:
        name: gnomad-api
    spec:
      serviceAccountName: gnomad-api
      containers:
        - name: app
          image: gnomad-api
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-conf
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: '1'
              memory: '2Gi'
            limits:
              cpu: '2'
              memory: '4Gi'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
      nodeSelector:
        cloud.google.com/gke-nodepool: 'main-pool'
