apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnomad-api
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gnomad-es-elastic-user
                  key: elastic
