- op: add
  path: /spec/nodeSets/-
  value:
    name: ingest
    count: 8
    config: # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
    podTemplate:
      metadata:
        labels:
          role: ingest
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cloud.google.com/gke-nodepool
                      operator: In
                      values:
                        - es-ingest
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          - name: install-plugins
            command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: '-Xms12g -Xmx12g'
            resources:
              requests:
                cpu: 3
                memory: 24Gi
              limits:
                cpu: 3.5
                memory: 24Gi
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: standard
          resources:
            requests:
              storage: 2000Gi
