apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../production
nameSuffix: -blue
labels:
  - includeSelectors: true
    pairs:
      deployment: blue

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/cloud.google.com~1backend-config
        value: '{{"ports": {{"80":"gnomad-backend-config-blue"}}}}'
    target:
      kind: Service
      name: gnomad-browser
configMapGenerator:
  - name: browser-conf
    behavior: merge
    literals:
      - API_URL=http://gnomad-browser-blue
  - name: api-conf
    behavior: merge
    literals:
      - ELASTICSEARCH_URL=http://gnomad-es-blue-http:9200
