apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
labels:
  - pairs:
      deployment: blue
      tier: production
nameSuffix: -blue
images:
  - name: gcr.io/exac-gnomad/gnomad-api
    newTag: '85dc023a'
  - name: gcr.io/exac-gnomad/gnomad-browser
    newTag: '85dc023a'
replacements:
  - source:
      fieldPath: metadata.name
      kind: Service
      name: gnomad-api
      version: v1
    targets:
      - fieldPaths:
          - spec.template.spec.containers.0.env.0.value
        options:
          delimiter: /
          index: 2
        select:
          group: apps
          kind: Deployment
          name: gnomad-browser
          version: v1
