apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gnomad.backendconfig.yaml
  - gnomad.frontendconfig.yaml
  - gnomad.managedcertificate.yaml
  - browser.service.yaml
  - reads.service.yaml
patches:
  - path: ingress-paths-patch.yaml
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: gnomad-ingress
        annotations:
          kubernetes.io/ingress.global-static-ip-name: gnomad-prod-global-ip
          networking.gke.io/managed-certificates: gnomad-prod-certificate
          networking.gke.io/v1beta1.FrontendConfig: 'gnomad-frontend-config'
