steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/gnomad-browser:$COMMIT_SHA'
      - '--destination=gcr.io/$PROJECT_ID/gnomad-browser:latest'
      - '--dockerfile=deploy/dockerfiles/browser/browser.dockerfile'
      - '--cache=true'
      - '--cache-ttl=168h'
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/exac-gnomad/gnomad-api:$COMMIT_SHA'
      - '--destination=gcr.io/exac-gnomad/gnomad-api:latest'
      - '--dockerfile=deploy/dockerfiles/browser/api.dockerfile'
      - '--cache=true'
      - '--cache-ttl=168h'
    waitFor: ['-'] # this tells cloudbuild to run this step concurrently with the browser build

timeout: 1800s
