steps:
  - name: 'us-central1-docker.pkg.dev/${PROJECT_ID}/tgg-sre-images/tgg-deploykit:testing-4'
    entrypoint: 'bash'
    args: ['./bluegreen-update.sh', '$SHORT_SHA']
    dir: '.cloudbuild'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gnomad-sj'
    secretEnv:
      - 'DEPLOY_KEY'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_DEPLOY_KEY/versions/latest
      env: 'DEPLOY_KEY'
